//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBSpecEntities : DbContext
    {
        public DBSpecEntities()
            : base("name=DBSpecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<x_biodata> x_biodata { get; set; }
        public virtual DbSet<x_address> x_address { get; set; }
        public virtual DbSet<x_identity_type> x_identity_type { get; set; }
        public virtual DbSet<x_marital_status> x_marital_status { get; set; }
        public virtual DbSet<x_rencana_jadwal> x_rencana_jadwal { get; set; }
        public virtual DbSet<x_employee> x_employee { get; set; }
        public virtual DbSet<x_schedule_type> x_schedule_type { get; set; }
        public virtual DbSet<x_undangan_detail> x_undangan_detail { get; set; }
        public virtual DbSet<x_time_period> x_time_period { get; set; }
        public virtual DbSet<x_undangan> x_undangan { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<x_riwayat_pendidikan> x_riwayat_pendidikan { get; set; }
        public virtual DbSet<x_addrbook> x_addrbook { get; set; }
        public virtual DbSet<x_client> x_client { get; set; }
        public virtual DbSet<x_menu_access> x_menu_access { get; set; }
        public virtual DbSet<x_menutree> x_menutree { get; set; }
        public virtual DbSet<x_placement> x_placement { get; set; }
        public virtual DbSet<x_riwayat_pekerjaan> x_riwayat_pekerjaan { get; set; }
        public virtual DbSet<x_role> x_role { get; set; }
        public virtual DbSet<x_timesheet> x_timesheet { get; set; }
        public virtual DbSet<x_timesheet_assessment> x_timesheet_assessment { get; set; }
        public virtual DbSet<x_userrole> x_userrole { get; set; }
        public virtual DbSet<x_online_test> x_online_test { get; set; }
        public virtual DbSet<x_online_test_detail> x_online_test_detail { get; set; }
        public virtual DbSet<x_test_type> x_test_type { get; set; }
        public virtual DbSet<x_religion> x_religion { get; set; }
        public virtual DbSet<x_sertifikasi> x_sertifikasi { get; set; }
    }
}
