//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class x_rencana_jadwal
    {
        public long id { get; set; }
        public long created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public Nullable<long> modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<long> deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
        public bool id_delete { get; set; }
        public string schedule_code { get; set; }
        public Nullable<System.DateTime> schedule_date { get; set; }
        public string time { get; set; }
        public Nullable<long> ro { get; set; }
        public Nullable<long> tro { get; set; }
        public Nullable<long> schedule_type_id { get; set; }
        public string location { get; set; }
        public string other_ro_tro { get; set; }
        public string notes { get; set; }
        public Nullable<bool> is_automatic_mail { get; set; }
        public Nullable<System.DateTime> sent_date { get; set; }
        public string status { get; set; }
    }
}
