//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class x_riwayat_pendidikan
    {
        public long id { get; set; }
        public string school_name { get; set; }
        public long biodata_id { get; set; }
        public string major { get; set; }
    }
}
