//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class x_timesheet
    {
        public long id { get; set; }
        public long created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public Nullable<long> modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<long> deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
        public bool is_delete { get; set; }
        public string status { get; set; }
        public long placement_id { get; set; }
        public Nullable<System.DateTime> timesheet_date { get; set; }
        public string start { get; set; }
        public string end { get; set; }
        public Nullable<bool> overtime { get; set; }
        public string start_ot { get; set; }
        public string end_ot { get; set; }
        public string activity { get; set; }
        public string user_approval { get; set; }
        public Nullable<System.DateTime> submitted_on { get; set; }
        public Nullable<System.DateTime> approved_on { get; set; }
        public string ero_status { get; set; }
        public Nullable<System.DateTime> sent_on { get; set; }
        public Nullable<System.DateTime> collected_on { get; set; }
    }
}
